server:
  port: 8860

#暴露全部的监控信息
management:
  endpoints:
    web:
      exposure:
        include: "*"

spring:
  application:
    name: spring-cloud-hystrix

eureka:
  instance:
    #服务注册中心实例的主机名
    hostname: localhost
  client:
    service-url:
      #服务注册中心的配置内容，指定服务注册中心的位置
      defaultZone: "http://admin:admin@${eureka.instance.hostname}:8888/eureka/"