server:
  port: 8801
spring:
  application:
    name: spring-cloud-ribbon

eureka:
  instance:
    #服务注册中心实例的主机名
    hostname: localhost
  client:
    service-url:
      #服务注册中心的配置内容，指定服务注册中心的位置
      defaultZone: "http://admin:admin@${eureka.instance.hostname}:8888/eureka/"


